services:

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ingestion:
    build: ./src/services/ingestion
    ports:
      - "8001:8001"
    environment:
      - INGESTION_VECTOR_STORE_URL=http://qdrant:6333
    depends_on:
      - qdrant

  vehicle_library:
    build: ./src/services/vehicle_library
    ports:
      - "8003:8003"

  query:
    build: ./src/services/query
    ports:
      - "8002:8002"
    environment:
      - QUERY_VECTOR_STORE_URL=http://qdrant:6333
      - QUERY_VEHICLE_LIBRARY_URL=http://vehicle_library:8003
    depends_on:
      - qdrant
      - vehicle_library
      - specification_library

  specification_library:
    build: ./src/services/specification_library
    ports:
      - "8004:8004"

volumes:
  qdrant_data:
